const QUESTION_CONTENT_MAX_LENGTH = 200;
const CORRECT_ANSWER_MAX_LENGTH = 200;
const OPTIONS_MAX_QUANTITY = 4;
const OPTIONS_MIN_QUANTITY = 2;

export {
  CORRECT_ANSWER_MAX_LENGTH,
  OPTIONS_MAX_QUANTITY,
  OPTIONS_MIN_QUANTITY,
  QUESTION_CONTENT_MAX_LENGTH,
};
